### ISSUE TITLE
Support configuration from the Rails secrets.yml file

### ISSUE THREAD

**Issue by nextmat** [librato/librato-rails#109]
The `secrets.yml` file was [added in Rails 4.1](http://edgeguides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml) to provide a consistent place for storing sensitive configuration information. It would be cool if for 4.1+ we could mine configuration definitely from that file if a `librato` key group was present, something like:

```yml
production:
  librato:
    user: 'user'
    token: 'xxx'
    ...
```

This would allow folks on newer rails to have one less config file to manage. Related: #107
