### ISSUE TITLE
Cannot start Rails in development environment if librato.yml doesn't have 'development' section

### ISSUE THREAD

**Issue by kulesa** [librato/librato-rails#27]
This is the stack trace I get when Rails attempts to start in development env: https://gist.github.com/4024626. My librato.yml looks just like described in the docs:

``` yaml
production:
  user: '<email>'
  token: '<token goes here>'
```
